# Generated by Django 5.2.7 on 2025-11-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wangumi_app", "0012_merge_20251118_1513"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffrole",
            name="name",
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
