# Generated by Django 5.2.7 on 2025-12-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangumi_app', '0017_merge_20251202_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('COMMENT', '创建了评论'), ('LIKE', '点赞了对象'), ('WANT', '想看番剧'), ('WATCHING', '在看番剧'), ('FINISHED', '已看番剧'), ('ITEM', '新建了条目')], max_length=20),
        ),
    ]
