# Generated by Django 5.2.7 on 2025-12-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wangumi_app", "0017_merge_20251202_1559"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[("season", "季度番同步"), ("weekly", "周合集生成")],
                        max_length=20,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("season", "季度番同步"), ("weekly", "周合集生成")],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "进行中"),
                            ("success", "成功"),
                            ("failure", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("created_count", models.IntegerField(default=0)),
                ("updated_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="anime",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="外部数据源的唯一标识，便于去重同步",
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="anime",
            name="is_season_featured",
            field=models.BooleanField(default=False, help_text="是否为当前季度推荐番"),
        ),
        migrations.AddField(
            model_name="anime",
            name="is_weekly_featured",
            field=models.BooleanField(default=False, help_text="是否为本周推荐番"),
        ),
        migrations.AddField(
            model_name="anime",
            name="season_quarter",
            field=models.CharField(
                blank=True,
                help_text="季度番季度：spring/summer/autumn/winter",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="anime",
            name="season_year",
            field=models.IntegerField(
                blank=True, help_text="季度番所在年份，例如 2025", null=True
            ),
        ),
    ]
