# Generated by Django 5.2.7 on 2025-12-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wangumi_app", "0018_alter_activity_action"),
        (
            "wangumi_app",
            "0018_synclog_anime_external_id_anime_is_season_featured_and_more",
        ),
    ]

    operations = []
